image: node:latest

# push to release branch to deploy
workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "release"
      when: never

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">>.npmrc
    - yarn publish
